---
title: "Drug-induced liver injury (DILI) risk screening: Free is as good as it gets"
author: "Matt Martin & DILI IMT Team"
date: "2/5/2021"
output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown Document for DILI Manuscript


```{r DILI List Concordance}
library(ggplot2)
library(data.table)
library(forcats)
library(dplyr)
library(stats)
dili <- fread(file.path("data", "dili_lists.csv"))
dili <- dili[!duplicated(drug)]
dili <- dili[!drug==""]

#create matrix of only 1/0 (+/-) for dili across the various datasets
#As opposed to our analysis, less and most were combined as positive and none and amb as negative
dili_mat <- as.matrix(dili[ , 4:21, with = F])
dili_cor <- list()
for(i in 1:ncol(dili_mat)){
  for(j in 1:ncol(dili_mat)){
    ivals <- dili_mat[,i]
    jvals <- dili_mat[,j]
    out <- list(iname = colnames(dili_mat)[i],
                jname = colnames(dili_mat)[j],
                pos = length(which(ivals==1 & jvals==1)),
                missed = length(which(!ivals==jvals)),
                match  = length(which(ivals==jvals)),
                neg = length(which(ivals==0 & jvals==0))
    )
    dili_cor[[paste(i,j)]] <- out
  }
}

dili_cor <- rbindlist(dili_cor)
dili_cor[ , concordance := round(match/(match+missed)*100,0)]
dili_cor[ , total_overlap := missed+match]

dili_cor[ , iN := max(total_overlap), by = iname]
dili_cor[ , jN := max(total_overlap), by = jname]


dili_cor <- dili_cor %>%
  mutate(iname = fct_reorder(iname, -iN)) %>%
  mutate(jname = fct_reorder(jname, jN))

dili_cor[ , i := as.numeric(iname)]
dili_cor[ , j := 19-as.numeric(jname)]

dili_cor[iname==jname, concordance := NA_real_]

dili_cor[, wmc := round(weighted.mean(concordance[!iname==jname], total_overlap[!iname==jname]),0)]


ggconcordance <-ggplot(dili_cor, aes(x = iname, y = jname)) + geom_point(size=NA) +
  geom_point(data = dili_cor[i<j], aes(color = concordance, size  = total_overlap)) + 
  geom_text(data = dili_cor[i>j], aes(label = concordance), color = "black", size = 4) +
  scale_x_discrete(position = "bottom") +
  scale_size_continuous(name = "Total Overlap", range = c(2,10)) +
  scale_color_continuous(name = "% Concordance") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(angle = 90, vjust=0.5, hjust=1, size = 12),
        axis.text.y = element_text(size = 12),
        axis.ticks = element_blank(),
        axis.title = element_blank(),
        plot.title = element_text(hjust = 0.5, size = 14)) +
  ggtitle(paste0("Overall Weighted Condorance = ", dili_cor$wmc,"%"))

tiff(file.path("figures", "Figure2_DILIListConcordance.tiff"), width = 10, height = 10, units = "in", res = 300)
ggconcordance
graphics.off()

```

```{r DILI IMT Data Collation}
library(ggplot2)

## DILI IMT Data Collation script

dat <- fread(file.path("data", "compiled_data.csv"))

#Number of drugs in complete dataset
nrow(dat)
#number of drug per dili annotation
dili_table <- table(dat$dili)
dili_table <- as.data.table(dili_table)
setnames(dili_table, "V1", "dili")
dili_table[dili == "Ambiguous", dili := "Amb"]
dili_table[ , dili := factor(dili, levels = c("None","Less","Most","Amb","Unknown"))]
setorder(dili_table, dili)
dili_table[ , dili_text := paste(dili, N, sep="\n")]
dili_table[ , col := c("#1B9E77","#D95F02", "#7570B3", "grey30","grey70")] #
dili_col <- dili_table$col
names(dili_col) <- dili_table$dili

g1 <- ggplot(data = dili_table, aes(x = 1, y = N, fill =  forcats::fct_rev(dili))) +
  geom_bar(stat = "identity", width = 1, position = "stack", show.legend = F) +
  geom_text(aes(label = dili_text), color = "white",
            position = position_stack(vjust = 0.5), size = 8) +
  coord_flip() +
  scale_fill_manual(name = "DILI Annotation", values = dili_col) +theme(
    axis.text.y = element_blank(),
    axis.title = element_blank(),
    panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
    panel.border = element_blank(), panel.background = element_blank(),
    axis.ticks = element_blank(),
    axis.text.x = element_text(size = 20))



tiff(file.path("figures", "Figure1partial_DiliBar.tiff"),
     width = 10, height = 4, units = "in", res = 300)
g1
graphics.off()

#Summary of Non-NA values for each element in data table
cat("Non missing values across entire data table")
apply(dat[dili %in% c("None","Less","Most"),
          list(kp,
               fu_liver, fu_bsa, kpuu,
               fu_liver_exp, fu_bsa_exp, kpuu_exp,
               bsep, thle, hepg2_glu, hepg2_gal, hepg2_72h)], 2, function(x) 
                 length(which(!is.na(x))))

# length(which(complete.cases(dat[dili %in% c("None","Less","Most"),
#  list(bsep, thle, hepg2_glu, hepg2_72h)])))


```
```{r DILI Boxplots}
library(ggplot2)
library(gridExtra)
library(car)
library(cowplot)
## Summary data plot of selected variables as a function of dili annotation
vars <- c("dose",
          "fsp3",
          "clogp",
          "clogd",
          "mw",
          "psa",
          "fu_liver_exp",
          "fu_bsa_exp",
          "kp",
          "kpuu_exp")

var_labs <-   c("log[10]~mg~Daily~Dose~(Dose)",
                "Fraction~C3~(Fsp^3)",
                "cLogP",
                "cLogD",
                "Molecular~Weight~(MW)",
                "Polar~Surface~Area~(PSA)",
                "Hepatic~Fraction~Unbound~(f[paste(u, ',', liver)])",
                "BSA~Fraction~Unbound~(f[paste(u, ',', BSA)])",
                "Hepatic~Partition~Coefficient~(Kp)",
                "Hepatic~Unbound~Partition~Coefficient~(Kp[uu])")


boxplots <- lapply(1:length(vars), function(i) {
  var <- vars[i]
  var_lab <- var_labs[i]
  print(var)
  print(var_lab)
  tmp <- dat[dili %in% c("None", "Less", "Most"),
             c("dili", var), with = F]
  tmp[ , dili := factor(dili, levels = c("None","Less","Most"))]
  
  kruskal <- kruskal.test(get(var) ~ dili, data = tmp)$p.value
  
  log_scale <- F
  if(min(tmp[ , (var), with = F], na.rm = T)<=0){log_scale <- F} else
    if(log10(max(tmp[ , (var), with = F], na.rm = T)/min(tmp[ , (var), with = F], na.rm = T))>2) log_scale <- T
  
  if(log_scale){
    tmp[ , (var) := lapply(.SD, log10), .SDcols = var]
  }
  
  stat_box_data <- function(y, upper_limit = (max(tmp[ , (var), with = F], na.rm = T)+0.5) * 1.15) {
    return( 
      data.frame(
        y = 0.95 * upper_limit,
        label = paste('count =', length(y), '\n',
                      'median =', round(median(y), 1), '\n')
      )
    )
  }
  
  
  title_text <- parse(text =  paste0("DILI~vs~",var_lab))
  subtitle_text <- paste0("(Kruskal-Wallis Pval = ",
                          signif(kruskal,2),
                          ")" )
  y_lab <- parse(text = var_lab)
  
  tsize <- 10
  g <- ggplot(tmp, aes_string(x = "dili", y = var, color = "dili")) +
    geom_boxplot(outlier.shape = NA, lwd = 1.2) + 
    geom_jitter(size=1, width = 0.1) +
    scale_color_brewer(palette = "Dark2") +
    stat_summary(fun.data = stat_box_data, 
                 geom = "text", 
                 hjust = 0.5,
                 vjust = 0.8,
                 size = tsize/3) +
    ylab(y_lab) + 
    xlab("DILI Class") +
    ggtitle(title_text, subtitle = subtitle_text) +
    theme(axis.text.x = element_text(size = tsize),
          axis.text.y = element_text(size = tsize),
          axis.title = element_text(size = tsize),
          plot.title = element_text(hjust = 0.5, size = tsize),
          plot.subtitle = element_text(hjust = 0.5, size = tsize*0.8),
          legend.text = element_text(size=tsize),
          legend.position = "none")
  return(g)
})

names(boxplots) <- vars

#Manuscript figure of dose and selected physchem props
tiff(file.path("figures", "Figure3_UnivariateBoxplots.tif"),
     width = 10, height = 6, units = "in", res = 300)
plot_grid(boxplots[["dose"]], boxplots[["clogp"]], boxplots[["fsp3"]], 
          nrow = 1, labels = "AUTO", label_size = 20)
graphics.off()

#alternate figure concept (moved to supplemental)
plot_grid(boxplots[["fu_liver_exp"]], boxplots[["fu_bsa_exp"]], boxplots[["kp"]], boxplots[["kpuu_exp"]],
          nrow = 2, labels = "AUTO", label_size = 20)

tiff(file.path("figures", "SuppFigure1_UnivariateBoxplotsRemaining.tif"),
     width = 12, height = 10, units = "in", res = 300)
#supplemental figure 1 (all continuous variables in grid format)
do.call("grid.arrange", c(boxplots[vars[c(4,5,7,8,9,10)]], ncol=3))
graphics.off()

#showing single plot... can change easily based on var name
boxplots[["dose"]]

```





```{r DILI Bar charts}

# DILI Bar charts for categorical or semi-continuous values

vars <- c("ion",
          "eccs",
          "bddcs",
          "bsep",
          "thle",
          "hepg2_glu",
          "hepg2_gal",
          "hepg2_72h",
          "mrp2",
          "mrp3",
          "mrp4")

var_labs <- c("Ionization~(Ion)",
              "Extended~Clearance~Classification~System~(ECCS)",
              "Biopharmaceutical~Drug~Disposition~Classification~System~(BDDCS)",
              "Bile~Salt~Export~Pump~Inhibition~(BSEP)",
              "THLE~Cytotoxicity~(THLE)",
              "HepG2~Glucose~Cytotoxicity~(HepG2[glu])",
              "HepG2~Galactose~Cytotoxicity~(HepG2[gal])",
              "HepG2~72~Hour~Cytotoxicity~(HepG2['72h'])",
              "Multidrug~Resistance~Protein~2~Inhibition~(MRP2)",
              "Multidrug~Resistance~Protein~3~Inhibition~(MRP3)",
              "Multidrug~Resistance~Protein~4~Inhibition~(MRP4)")

leg_labs <- c("Ion",
              "ECCS",
              "BDDCS",
              "BSEP",
              "THLE",
              "HepG2[glu]",
              "HepG2[gal]",
              "HepG2['72h']",
              "MRP2",
              "MRP3",
              "MRP4")

tmp <- dat[dili %in% c("None", "Less", "Most"),
           list(dili, ion, eccs, bddcs, bsep, thle,
                hepg2_glu,hepg2_gal,hepg2_72h,
                mrp2,mrp3,mrp4)]
#Class 0 is essentially missing information
tmp[bddcs=="Class 0" , bddcs := NA]
tmp[ , dili := factor(dili, levels = c("None","Less","Most"))]

#convert safety assay -log10 potency values to categorical values
tmp[ , bsep := paste0("Class ", as.integer(bsep/2))]
tmp[ , thle := paste0("Class ", as.integer(thle/2))]
tmp[ , hepg2_glu := paste0("Class ", as.integer(hepg2_glu/2))]
tmp[ , hepg2_gal := paste0("Class ", as.integer(hepg2_gal/2))]
tmp[ , hepg2_72h := paste0("Class ", as.integer(hepg2_72h/2))]
tmp[ , mrp2 := paste0("Class ", as.integer(mrp2/2))]
tmp[ , mrp3 := paste0("Class ", as.integer(mrp3/2))]
tmp[ , mrp4 := paste0("Class ", as.integer(mrp4/2))]

tmp[bsep == "Class NA", bsep := NA]
tmp[thle == "Class NA", thle := NA]
tmp[hepg2_glu == "Class NA", hepg2_glu := NA]
tmp[hepg2_gal == "Class NA", hepg2_gal := NA]
tmp[hepg2_72h == "Class NA", hepg2_72h := NA]
tmp[mrp2 == "Class NA", mrp2 := NA]
tmp[mrp3 == "Class NA", mrp3 := NA]
tmp[mrp4 == "Class NA", mrp4 := NA]

tmp <- droplevels(tmp)


barplots <- lapply(1:length(vars), function(i){
  var <- vars[i]
  var_lab <- var_labs[i]
  leg_lab <- leg_labs[i]
  print(var)
  print(var_lab)
  chisq <- chisq.test(table(tmp$dili, tmp[ , get(var)]))$p.value
  tmp1 <- tmp[!is.na(get(var)),
              .N, by = c("dili", var)]
  tmp1[ , perc := N/sum(N)*100, by = c("dili")]
  tmp1[perc>5 , label :=  paste0(N, " (", sprintf("%.0f", perc), "%)")]
  
  title_text <- parse(text =  paste0("DILI~vs~",var_lab))
  subtitle_text <- paste0("(Chi-Square Pval = ", signif(chisq,2), ")" )
  l_lab <- parse(text = leg_lab)
  
  tsize <- 10
  ggplot(tmp1,
         aes_string(x = "dili", y = "perc", group=var, fill=var)) +
    geom_bar(position = "stack", stat = "identity") + 
    geom_text(aes(label = label), position = position_stack(vjust = 0.5),
              size = tsize/3, color = 'grey10') + 
    scale_fill_brewer(palette = "Set1") + 
    ylab("Proportion of total (within each DILI class)") +
    xlab("DILI Class") + 
    ggtitle(title_text, subtitle = subtitle_text) +
    theme(axis.text.x = element_text(size = tsize),
          axis.text.y = element_text(size = tsize),
          axis.title = element_text(size = tsize),
          plot.title = element_text(hjust = 0.5, size = tsize),
          plot.subtitle = element_text(hjust = 0.5, size = tsize*0.8),
          legend.text = element_text(size=tsize),
          legend.title = element_text(size=tsize)) +
    guides(fill=guide_legend(title=l_lab))
})

names(barplots) <- vars

#manuscript figure
tiff(file.path("figures", "Figure4_UnivariateStackedBarCharts.tif"),
     width = 12, height = 6, units = "in", res = 300)
plot_grid(barplots[["ion"]], barplots[["bddcs"]], 
          nrow = 1, labels = "AUTO", label_size = 20)
graphics.off()

tiff(file.path("figures", "SuppFigure2_UnivariateStackedBarCharts.tif"),
     width = 12, height = 24, units = "in", res = 300)
do.call("grid.arrange", c(barplots[vars[4:11]], ncol=2))
graphics.off()

#example of single figure output
barplots[["ion"]]

```






```{r DILI Variable Correlation}
source("Dili_Screening_Data_Prep.R")
library(corrplot)

cdat <- as.data.table(data_prep(dat,
                                dili_positive = c("Most"),
                                dili_negative = c("None", "Less"),
                                col_sets = c("dose", "cmax", 
                                             "physchem", "bddcs", "insilico_pk",
                                             "invitro_pk_exp", "invitro_safety"),
                                required_non_missing = c("dili"),
                                allowed_fraction_missing = 0.8,
                                fill_missing = F,
                                remove_correlated_cutoff = 1)$DATA)

cor_vars <- c("dose", "cmax", "mw","fsp3","clogp","clogd","psa",
              "fu_liver_exp","fu_bsa_exp","kp","kpuu_exp",
              "bsep","thle","hepg2_glu","hepg2_gal", "hepg2_72h",
              "mrp2", "mrp3", "mrp4")

cmat <- cor(as.matrix(cdat[ , cor_vars, with = F]), use = "complete.obs")
cmat[cmat==1] <- 0

labs <- c("Dose", "Cmax", "MW", ":Fsp^3", "cLogP", "cLogD", "PSA",
          ":f[paste(u, ',', liver)]", ":f[paste(u, ',', BSA)]", "Kp", ":Kp[uu]",
          "BSEP", "THLE", ":HepG2[glu]", ":HepG2[gal]", ":HepG2['72h']",
          "MRP2", "MRP3", "MRP4")

colnames(cmat) <- labs
rownames(cmat) <- labs

cplot <- corrplot(cmat, type = "upper", tl.col = "black", method = "circle")

tiff(file.path("figures", "Figure5_CorrPlot.tif"),
     width = 7, height = 6, units = "in", res = 300)
corrplot(cmat, type = "upper", tl.col = "black", method = "circle")
graphics.off()

```


```{r DILI Dataset Generation}
#Create modeling ready datasets with varying combinations of parameter sets
source("Dili_Screening_Data_Prep.R")

#remove correlated variables based on different cutoffs
cor_cutoffs <- c(1.0, 0.6)

fs_rn <- rbindlist(list(
  expand.grid(fs = c("dose", "dose|physchem", "dose|physchem|bddcs"),
              rn = "dili|dose",
              cc = cor_cutoffs),
  expand.grid(fs = c("dose", "dose|physchem", "dose|physchem|bddcs", "dose|physchem|invitro_pk"),
              rn = "dili|dose|kp",
              cc = cor_cutoffs),
  expand.grid(fs = c("dose", "dose|physchem", "dose|physchem|bddcs", "dose|physchem|invitro_safety"),
              rn = "dili|dose|thle|bsep",
              cc = cor_cutoffs),
  expand.grid(fs = c("dose", "dose|physchem", "dose|physchem|invitro_safety"),
              rn = "dili|dose|mrp2",
              cc = cor_cutoffs)
))
fs_rn[ , fsrn := paste(fs, rn, cc, sep = "|||")]

model_dat_list <- list()
model_dat_list <- lapply(1:nrow(fs_rn), function(i){
  #print(i)
  col_sets <- unlist(strsplit(as.character(unlist(fs_rn[i, "fs"])), "|", fixed = T))
  req_sets <- unlist(strsplit(as.character(unlist(fs_rn[i, "rn"])), "|", fixed = T))
  cor_cutoff <- unlist(fs_rn[i, "cc"])
  
  model_dat <- data_prep(dat,
                         dili_positive = c("Most"),
                         dili_negative = c("None", "Less"),
                         col_sets = col_sets,
                         required_non_missing = req_sets,
                         allowed_fraction_missing = 0.2,
                         fill_missing = T,
                         remove_correlated_cutoff = cor_cutoff)
  
  return(model_dat)
}
)
names(model_dat_list) <- fs_rn$fsrn

saveRDS(model_dat_list, file.path("output", "model_dat_list_ms.RDS") )

```

```{r DILI Model Suite Generation}
library(dplyr)
library(forcats)
source("DILI_Screening_Modeling.R")
#requires dose as a parameter
model_indexes <- names(model_dat_list)[grep("^dose.*1$", names(model_dat_list))]

#simple switch to prevent rerunning of models if not necessary
RERUN_MODELS <- TRUE

if(RERUN_MODELS == TRUE) {
  dili_models <- lapply(model_indexes,
                        function(i) {
                          print(i)
                          DATA <- model_dat_list[[i]]$DATA
                          models <- dili_model_suite(DATA,
                                                     models2run = c("ranger"),
                                                     sampling = "down",
                                                     cvnumber = 5,
                                                     cvrepeat = 5)
                          return(models)
                        }
                        
  )

  names(dili_models) <- model_indexes
  
  saveRDS(dili_models, file.path("output", "dili_models_ms.RDS") )
} else {
  dili_models <- readRDS(file.path("output", "dili_models_ms.RDS") )
}

#condense down available model results
dili_model_results <- rbindlist(lapply(1:length(dili_models),
   function(i){
     rbindlist(lapply(1:length(dili_models[[i]]), 
                      function(j) {
                        
      dataset_name <- names(dili_models)[i]
      model_name <- names(dili_models[[i]])[j]
      N <- length(unique(dili_models[[i]][[j]]$pred$rowIndex))
      stats <- dili_models[[i]][[j]]$results[as.numeric(rownames(dili_models[[i]][[j]]$bestTune)),]
      out <- as.data.table(cbind(data_feature_coff_name = dataset_name,
                                 model = model_name,
                                 N = N,
                                 stats))
      return(out)
      
                      }), fill = T )
   }), fill = T)

dili_model_results[ , c("features", "dataset", "cor_cutoff") := tstrsplit(data_feature_coff_name, "|||", fixed = T)]    

dili_model_results <- dili_model_results[!is.na(ROC)]
dili_model_results[ , dataset_label := ifelse(dataset=="dili|dose", paste0("Full Dataset\n(",N," drugs)"), ifelse(dataset=="dili|dose|kp",paste0("TK Dataset\n(",N," drugs)"), paste0("Safety Dataset\n(",N," drugs)")))]
dili_model_results[ , dataset_label := factor(dataset_label, levels = unique(dataset_label))]
dili_model_results[ , feature_label := gsub("|"," + ", features, fixed =T)]

dili_model_results[ , rank_by_dataset := rank(-ROC), by = list(model, dataset)]


dili_model_results_subset <- dili_model_results[!grepl("cmax|insilico_pk", features) &
                                                  grepl("dose", features, fixed = T) & 
                                                  !grepl("mrp2", dataset) &
                                                  model == "rrf_dn_model"]
dili_model_results_subset[ , ROC_MEAN := median(ROC), by = list(data_feature_coff_name)]
dili_model_results_subset[ , rank_by_dataset := rank(-ROC_MEAN), by = list(model, dataset)]

y_labels <- dili_model_results_subset$feature_label 
names(y_labels) <- dili_model_results_subset$data_feature_coff_name

ggmodel <- dili_model_results_subset %>%
  mutate(data_feature_coff_name = fct_reorder(data_feature_coff_name, desc(ROC_MEAN))) %>%
  ggplot(aes(x = ROC, y = data_feature_coff_name)) + #, color = model)) +
  geom_point(size = 4,
             position=position_dodge(.9)) +
  geom_errorbar(aes(xmin=ROC-ROCSD, xmax = ROC+ROCSD), 
                size = 2, width = 0.5,
                position=position_dodge(.9), alpha=0.3) +
  scale_color_brewer(palette = "Dark2") +
  scale_y_discrete(name = "Parameter Sets", labels = y_labels) +
  xlab("Mean AUC +/- AUC SD (5 x 5-fold CV)") + 
  theme_bw(base_size = 18)+
  guides(color=FALSE) +
  facet_grid(rows = vars(dataset_label),
             #cols = vars(model),
             scales = "free_y",
             space = "free_y",
             drop = T)

tiff(file.path("figures", "Figure6_ModelResults.tif"),
     width = 10, height = 6, units = "in", res = 300)
  ggmodel
graphics.off()

ggmodel


```

```{r DILI Variable Importance}

#Explore variable importance metrics to ascertain relative value while accounting
#for variable correlation and other confounders

library(permimp)
library(ggplot2)
library(ggrepel)
library(cowplot)
library(caret)
library(randomForest)

model_dat_names <- c("dose|physchem|bddcs|||dili|dose|||1",
                     "dose|physchem|invitro_pk|||dili|dose|kp|||1",
                     "dose|physchem|invitro_safety|||dili|dose|thle|bsep|||1",
                     "dose|physchem|bddcs|||dili|dose|||0.6",
                     "dose|physchem|invitro_pk|||dili|dose|kp|||0.6",
                     "dose|physchem|invitro_safety|||dili|dose|thle|bsep|||0.6")

RERUN_VI <- TRUE

if(RERUN_VI == TRUE) {
  VI.list <- lapply(model_dat_names, function(m) {
    DATA <- model_dat_list[[m]]$DATA
    
    set.seed(123456)
    rf <- randomForest(Y ~., 
                       data = DATA,
                       sampsize = rep(min(table(DATA$Y)),
                                      length(unique(DATA$Y))), #equ to down sampling
                       ntree = 1000,
                       keep.forest = TRUE,
                       keep.inbag = TRUE
    )
    
    rf_vi <- permimp(rf, conditional = F, do_check = F)
    
    tmp <- unlist(strsplit(m, split = "|||", fixed = T))
    
    out <- as.data.table(list(
      parameter_set = tmp[1],
      dataset = tmp[2],
      cor_cutoff = tmp[3],
      variable = names(rf_vi$values),
      importance = rf_vi$values)
    )
    return(out)
  })
  
  saveRDS(VI.list, file.path("output", "vi_list.RDS") )
} else {
  VI.list <- readRDS( file.path("output", "vi_list.RDS") ) 
}

VI <- rbindlist(VI.list)

VI[ , importance := importance+0.001]

VI <- dcast.data.table(VI, parameter_set + dataset + variable ~ cor_cutoff, 
                       fun.aggregate = max, value.var = "importance", fill = 0.0001)
setnames(VI, c("0.6","1"), c("ImpRem", "ImpAll"))

VI[ , dataset_label := ifelse(dataset=="dili|dose",
                              "Full Dataset",
                              ifelse(dataset=="dili|dose|kp",
                                     "TK Dataset",
                                     "Safety Dataset"))]
VI[ , dataset_label := factor(dataset_label, levels = unique(dataset_label))]

variable_name_map <- as.data.table(list(
  variable = c(
    "dose",
    "fsp3",
    "bddcs",
    "clogp",
    "clogd",
    "eccs",
    "ion",
    "mw",
    "psa",
    "fu_liver",
    "fu_bsa",
    "kp",
    "kpuu",
    "bsep",
    "thle",
    "hepg2_glu",
    "hepg2_gal",
    "hepg2_72h"
  ),
  label = c(
    "Dose",
    "Fsp^3",
    "BDDCS",
    "cLogP",
    "cLogD",
    "ECCS",
    "Ion",
    "MW",
    "PSA",
    "f[paste(u, ',', liver)]", 
    "f[paste(u, ',', BSA)]",
    "Kp", 
    "Kp[uu]",
    "BSEP", 
    "THLE", 
    "HepG2[glu]", 
    "HepG2[gal]", 
    "HepG2['72h']"
  )))

VI <- merge(VI, variable_name_map, by = "variable")

ggvi <- ggplot(VI, aes(y = ImpRem, x = ImpAll)) + geom_point() +
  scale_x_log10(name = "Permuted Variable Importance (All Parameters)") + 
  scale_y_log10(
    name = "Permuted Variable Importance (Correlated Parameters Removed)",
    breaks = 10^(-4:3),
    labels = c("Removed",10^(-3:3))
  ) +
  geom_label_repel(aes(label = label),
                   size = 6,
                   box.padding   = 0.35, 
                   point.padding = 0.5,
                   segment.color = 'grey50',
                   parse = T) +
  facet_wrap(vars(dataset_label), ncol = 3) +
  theme(
    axis.text.x = element_text(size = 16),
    axis.text.y = element_text(size = 16),
    axis.title.x = element_text(size = 16),
    axis.title.y = element_text(size = 16),
    strip.text = element_text(size = 16)
  )   

tiff(file.path("figures", "Figure7_VariableImportance.tif"),
     width = 18, height = 7, units = "in", res = 300)
ggvi 
graphics.off()

ggvi

```

```{r DILI Model Deep Dive}
library(data.table)
library(parallel)
library(ggplot2)
library(ggrepel)
source("DILI_Screening_Modeling.R")

#create data.frame of all combination of key parameters
vars1 <- c("fsp3", "clogp", "clogd", "ion", "mw", "bddcs", "kp", "kpuu")
vars <- lapply(1:length(vars1), function(m) as.data.frame(t(combn(vars1, m = m))))
vars <- rbindlist(vars, fill = T)
vars <- cbind(dose="dose", vars)
var_names <- apply(vars, 1, function(x) paste(x[which(!is.na(x))], collapse = " + "))

labs1 <- c("Fsp^3", "cLogP", "cLogD", "Ion", "MW", "BDDCS", "Kp", "Kp[uu]")
labs <- lapply(1:length(labs1), function(m) as.data.frame(t(combn(labs1, m = m))))
labs <- rbindlist(labs, fill = T)
labs <- cbind(dose="Dose", labs)
lab_names <- apply(labs, 1, function(x) paste(x[which(!is.na(x))], collapse = " + "))

DATA <- data_prep(dat,
                  dili_positive = c("Most"),
                  dili_negative = c("None", "Less"),
                  col_sets = c("dose","physchem","bddcs","invitro_pk"),
                  required_non_missing = c("dili","dose", "kp"),
                  allowed_fraction_missing = 0.2,
                  fill_missing = T,
                  remove_correlated_cutoff = 1)$DATA

RERUN_DD_MODEL <- TRUE

if(RERUN_DD_MODEL == TRUE) {
  
  start <- Sys.time()
  print(start)
  dili_dd_models <- lapply(1:nrow(vars),
                           function(i) {
                             print(i)
                             v <- unlist(vars[i,])
                             v <- v[!is.na(v)]
                             TMP <- DATA[ , c("Y", v)]
                             models <- dili_model_suite(TMP,
                                                        models2run = "ranger",
                                                        sampling = "down",
                                                        cvnumber = 5,
                                                        cvrepeat = 1)
                             return(models)
                           }
  )
  
  stop <- Sys.time()
  print(stop-start)
  
  names(dili_dd_models) <- var_names
  
  saveRDS(dili_dd_models,
          file.path("output", "dili_dd_models_ms.RDS") )
} else { 
  dili_dd_models <- readRDS(file.path("output", "dili_dd_models_ms.RDS"))
}

dili_dd_dat <- rbindlist(lapply(1:length(dili_dd_models),
                                function(i){
                                  rbindlist(lapply(1:length(dili_dd_models[[i]]), 
                                                   function(j) {
                                                     
                                                     var_name <- names(dili_dd_models)[i]
                                                     lab_name <- lab_names[i]
                                                     model_name <- names(dili_dd_models[[i]])[j]
                                                     stats <- dili_dd_models[[i]][[j]]$results[as.numeric(rownames(dili_dd_models[[i]][[j]]$bestTune)),]
                                                     out <- as.data.table(cbind(var_names = var_name,
                                                                                lab_names = lab_name,
                                                                                model = model_name,
                                                                                stats))
                                                     return(out)
                                                     
                                                   }), fill = T )
                                }), fill = T)

dili_dd_dat <- dili_dd_dat[!is.na(ROC)]    


dili_dd_dat[ , dose := grepl("dose", var_names)]
dili_dd_dat[ , fsp3 := grepl("fsp3", var_names)]
dili_dd_dat[ , clogp := grepl("clogp", var_names)]
dili_dd_dat[ , bddcs := grepl("bddcs", var_names)]
dili_dd_dat[ , kp := grepl("kp", var_names)]
dili_dd_dat[ , ion := grepl("ion", var_names)]
dili_dd_dat[ , kpuu := grepl("kpuu", var_names)]
dili_dd_dat[ , clogd := grepl("clogd", var_names)]

dili_dd_dat[ , param_cnt := nchar(var_names) - nchar(gsub("+","", var_names, fixed = T)) + 1]
dili_dd_dat[ , rnk_all := rank(-ROC), by = list(param_cnt, model)]
dili_dd_dat[bddcs==F, rnk_sans_bddcs := rank(-ROC), by = list(param_cnt, model)]

dili_dd_tmp <- dili_dd_dat[model=="rrf_dn_model" & bddcs==F,
                           list(ROC = mean(ROC)),
                           by = list(var_names, lab_names, param_cnt)]
dili_dd_tmp[ , ROC := round(ROC, 2)]
dili_dd_tmp[ , rnk_out := rank(-ROC, ties.method = "min"), by = list(param_cnt)]
setkey(dili_dd_tmp, "param_cnt", "rnk_out")
dili_dd_tmp[ , ordr := 1:.N, by = .(param_cnt)]

dose_auc <- round(dili_model_results[data_feature_coff_name=="dose|||dili|dose|kp|||1", ROC],2)
dose_bbdcs_auc <- round(dili_dd_dat[var_names=="dose + bddcs", ROC],2)
dose_physchem_auc <- round(dili_model_results[data_feature_coff_name=="dose|physchem|||dili|dose|kp|||1", ROC],2)

tsize <- 8
ggdd <- ggplot(dili_dd_tmp[rnk_out<=3 & param_cnt<=8], aes(x = as.factor(param_cnt), y = ROC)) + 
  geom_hline(yintercept = dose_bbdcs_auc, color = "grey25") +
  geom_hline(yintercept = dose_physchem_auc, color = "grey25") +
  annotate(geom = 'text', label = 'Dose + BDDCS', x = "8", y = dose_bbdcs_auc, hjust = 0.9, vjust = 1, size = tsize/2.5) +
  annotate(geom = 'text', label = 'Dose + Physchem', x = "8", y = dose_physchem_auc, hjust = 0.9, vjust = 1, size = tsize/2.5) +
  geom_jitter(aes(color = as.factor(rnk_out)),
              width = 0.1, 
              size = tsize/2.5,
              height = 0) + 
  geom_text(data = dili_dd_tmp[ordr<=5 & rnk_out <=3 & param_cnt<7],
            aes(x = as.factor(param_cnt),
                y = ifelse(param_cnt > 3 & param_cnt %% 2 == 0,
                           0.7-ordr/50,
                           0.9-ordr/50),
                label = lab_names,
                color = as.factor(rnk_out)),
            size = tsize/2.5,
            parse = T) +
  geom_jitter(data = dili_dd_tmp[rnk_out>3], aes(x = as.factor(param_cnt), y = ROC),
              width = 0.2,
              size =  tsize/3,
              height = 0, color = "grey50") + 
  scale_color_brewer(name = "Model Rank", palette = "Dark2") +
  xlab("Number of Parameters") +
  scale_y_continuous(name = "Mean AUC", breaks = seq(0.6, 0.9, 0.05)) +
  ggtitle("Model performance as a function of the number of input parameters",
          subtitle = "An exhaustive search (Top 3 models highlighted)") +
  theme(legend.position="top", 
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        axis.text.x = element_text(size = tsize),
        axis.text.y = element_text(size = tsize),
        axis.title.x = element_text(size = tsize),
        axis.title.y = element_text(size = tsize),
        plot.title = element_text(size = tsize*1.2,hjust = 0.5),
        plot.subtitle = element_text(size = tsize, hjust = 0.5),
        legend.text = element_text(size = tsize),
        legend.title = element_text(size = tsize))

tiff(file.path("figures", "Figure8_ExhaustiveModelSearch.tiff"),
     width = 10, height = 6, units = "in", res = 300)
ggdd
graphics.off()

ggdd

```
